m=float(input('Uma distancia em metros'))
km=(m/1000)
hm=(m/100)
dam=(m/10)
dm=(m*10)
cm=(m*100)
mm=(m*1000)
print('{} metros equivale a {} kilometros'.format(m,km))
print('{} metros equivale a {} hectometros'.format(m,hm))
print('{} metros equivale a {} decametros'.format(m,dam))
print('{} metros equivale a {} decimetro'.format(m,dm))
print('{} metros equivale a {} centimetros'.format(m,cm))
print('{} mettos equivale a {} milimetros'.format(m,mm))